.\" (c) Copyright 2022 Richard W. Marinelli
.\"
.\" This work is licensed under the GNU General Public License (GPLv3).  To view a copy of this license, see the
.\" "License.txt" file included with this distribution or visit http://www.gnu.org/licenses/gpl-3.0.en.html.
.\"
.ad l
.TH CXLVERS 3 2022-06-04 "Ver. 1.1.0" "CXL Library Documentation"
.nh \" Turn off hyphenation.
.SH NAME
\fBcxlvers\fR - return CXL library version.
.SH SYNOPSIS
\fB#include "cxl/lib.h"\fR
.HP 2
\fBchar *cxlvers(void);\fR
.SH DESCRIPTION
The \fBcxlvers\fR() routine returns a human-readable library version string.
.SH SEE ALSO
cxl(3)
