.\" (c) Copyright 2022 Richard W. Marinelli
.\"
.\" This work is licensed under the GNU General Public License (GPLv3).  To view a copy of this license, see the
.\" "License.txt" file included with this distribution or visit http://www.gnu.org/licenses/gpl-3.0.en.html.
.\"
.ad l
.TH DEQ 3 2022-06-04 "Ver. 1.1.0" "CXL Library Documentation"
.nh \" Turn off hyphenation.
.SH NAME
\fBdeq\fR - compare one datum to another and return Boolean result.
.SH SYNOPSIS
\fB#include "cxl/datum.h"\fR
.HP 2
\fBbool deq(const Datum *pDatum1, const Datum *pDatum2, ushort dflags);\fR
.SH DESCRIPTION
The \fBdeq\fR() function compares the two datums pointed to by \fIpDatum1\fR and \fIpDatum2\fR for equality,
subject to the operation flag in \fIdflags\fR, which is either \fBDOpIgnore\fR or zero.  If \fIdflags\fR is
\fBDOpIgnore\fR, case is ignored when comparing datums that contain strings; otherwise, case is significant.
The datums are considered identical if they are the same type and have matching values.
.PP
Note that the \fBDOpIgnore\fR flag is identical to the \fBAOpIgnore\fR flag that is used for array operations;
that is, they are defined to be the same value and thus, can be used interchangeably.
.SH RETURN VALUES
\fBdeq\fR returns true if the datums match, otherwise false.
.SH SEE ALSO
aeq(3), cxl(3), cxl_array(7), cxl_datum(7), excep(3)
