.\" (c) Copyright 2022 Richard W. Marinelli
.\"
.\" This work is licensed under the GNU General Public License (GPLv3).  To view a copy of this license, see the
.\" "License.txt" file included with this distribution or visit http://www.gnu.org/licenses/gpl-3.0.en.html.
.\"
.ad l
.TH FFCLOSE 3 2022-11-04 "Ver. 1.2" "CXL Library Documentation"
.nh \" Turn off hyphenation.
.SH NAME
\fBffclose\fR, \fBffclosekeep\fR - close a fast file.
.SH SYNOPSIS
\fB#include "cxl/fastio.h"\fR
.HP 2
\fBint ffclose(FastFile *\fIpFastFile\fB);\fR
.HP 2
\fBint ffclosekeep(FastFile *\fIpFastFile\fB);\fR
.SH DESCRIPTION
These functions close the fast file pointed to by \fIpFastFile\fR.  \fBffclose\fR() closes the file and also releases the
memory associated with the \fBFastFile\fR object.  \fBffclosekeep\fR() closes the file, but keeps the \fBFastFile\fR
object and its buffers intact, for subsequent manipulation by the caller.  In this case, the file object must be freed
with \fBfffree\fR() when it is no longer needed.
.SH RETURN VALUES
If successful, \fBffclose\fR() and \fBffclosekeep\fR() return zero.  They return a negative integer on failure,
and set an exception code and message in the CXL Exception System to indicate the error.
.SH SEE ALSO
cxl(3), cxl_fastio(7), excep(3), fffree(3)
