.\" (c) Copyright 2022 Richard W. Marinelli
.\"
.\" This work is licensed under the GNU General Public License (GPLv3).  To view a copy of this license, see the
.\" "License.txt" file included with this distribution or visit http://www.gnu.org/licenses/gpl-3.0.en.html.
.\"
.ad l
.TH HFREE 3 2022-06-04 "Ver. 1.1.0" "CXL Library Documentation"
.nh \" Turn off hyphenation.
.SH NAME
\fBhfree\fR - free a hash table.
.SH SYNOPSIS
\fB#include "cxl/hash.h"\fR
.HP 2
\fBvoid hfree(HashTable *pHashTable);\fR
.SH DESCRIPTION
The \fBhfree\fR() function frees all memory associated with the hash table pointed to by \fIpHashTable\fR; that
is, it deletes the hash table.  The routine first calls hclear(3) to free all the nodes, then calls free(3) on
the remaining control structures.
.PP
This routine should be called to free memory associated with a hash table when it is no longer needed.
.SH SEE ALSO
cxl(3), cxl_hash(7), free(3), hclear(3)
